chore(tooling,tests): fix mypy error
This could be further refactored to remove this fixture entirely; it seems request is never used. No diffs in fixtures with this change.

Fixes mypy 1.15.0 error:
tests/cancun/eip4788_beacon_root/conftest.py:170: error: Incompatible return value type (got "Any | Account", expected "Address")  [return-value]